name = "uv-cloudflare-workers-example"
main = "src/worker.py"
compatibility_flags = ["python_workers"]
compatibility_date = "2025-03-16"

[observability.logs]
enabled = true

[[rules]]
globs = ["vendor/**"]
type = "Data"
fallthrough = true
